### PR TITLE
Assignment2

### PR DESCRIPTION
**Pull request by rilwanhaq**

### CODE REVIEW

**Comment by rilwanhaq** [comment]
reactassignment 2

**Comment by rilwanhaq** [comment]
reactassignment 2

**Review by 10534549 — COMMENTED** [review]
everything seems good but in ur, output screen make sure to give the alignments to the center of the page not left

**Comment by rilwanhaq** [comment]
> everything seems good but in ur, output screen make sure to give the alignments to the center of the page not left

its already in center i croped the output so when you open the screenshot its shows to the left

**Comment by 10534549** [comment]
> > everything seems good but in ur, output screen make sure to give the alignments to the center of the page not left
> 
> its already in center i croped the output so when you open the screenshot its shows to the left

ok then you can merge it it is good

**Comment by rilwanhaq** [comment]
> > > everything seems good but in ur, output screen make sure to give the alignments to the center of the page not left
> > 
> > 
> > its already in center i croped the output so when you open the screenshot its shows to the left
> 
> ok then you can merge it it is good

thanks and let me upload the full screen
Assignment-2-fullscreenshot
shot for reference

**Comment by saikiransathpadi** [comment]
correct

**Pull request merged**
